name: kusa_baseball
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # ... 他のパッケージ
  firebase_core: ^3.1.1 # バージョンは最新を確認
  firebase_messaging: ^15.0.1 # バージョンは最新を確認
  flutter_riverpod: ^2.5.1 # 例：バージョンを指定
  dio: ^5.4.3 # 例：バージョンを指定
  flutter_secure_storage: ^9.1.1
  geolocator: ^12.0.0
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0  # (規約/ポリシーのWebビュー起動用)

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png
  android_12:
    image: assets/splash.png
    color: "#FFFFFF"
  fullscreen: true